[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
hiddenhand = "9chPz3vJDeU7gr4zBtDreJUpVLKbqwrKoQBQQjT1SF5X"

[programs.localnet]
hiddenhand = "9chPz3vJDeU7gr4zBtDreJUpVLKbqwrKoQBQQjT1SF5X"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[hooks]
